### ISSUE TITLE
Environments are not created automatically (Prod &Dev) on Azure DevOps Pipelines

### ISSUE THREAD

**Issue by yelizkilinc** [Azure/mlops-v2#107]
### Describe the bug or the issue that you are facing

3.10 Under Pipelines, select Environments and ensure both "Prod" and "Dev" environments are created. Create the "Dev" environment manually, if necessary. -> I followed deployment guide. It worked fine for CLIv2-bicep-Classical parameters but there is no env created automatically.

### Steps/Code to Reproduce

Follow the deployment guide till 3.10 by selecting CLIv2-bicep-Classical parameters

### Expected Output

3.10 step should be validated but there is no env on AzureDevOps pipelines.

### Versions

-

### Which platform are you using for deploying your infrastrucutre?

Azure DevOps (ADO)

### What are you using for deploying your infrastrucutre?

Bicep

### Are you using Azure ML CLI v2 or Azure ML Python SDK v2

Azure ML CLI v2

### Describe the example that you are trying to run?

3.10 step is not happening when I follow the deployment guide in order.

**Comment by sdonohoo** [comment]
This issue is under investigation. Autocreate behavior for environments when referenced changed last October. Investigating to determine fix or workaround. For now, deployment guide has been updated (https://github.com/Azure/mlops-v2/pull/108) to include guidance for manually creating environments prior to running the infra pipeline.

**Comment by setuc** [comment]
Closing this. @yelizkilinc  I hope the updated documentation has resolved your issue.

**Comment by setuc** [comment]
@yelizkilinc I hope this has resolved your issue.
