### ISSUE TITLE
CV Job Fails with error in train.py (standard project template)

### ISSUE THREAD

**Issue by jplummer01** [Azure/mlops-v2#93]
### Describe the bug or the issue that you are facing

<img width="325" alt="image" src="https://user-images.githubusercontent.com/10486962/217639694-0b4a9b62-761a-454b-8702-1fe6dec82f60.png">

<img width="859" alt="image" src="https://user-images.githubusercontent.com/10486962/217639760-fde89bbf-f0d5-46a7-8e65-3ceeb519ddf3.png">

### Steps/Code to Reproduce

Deploy the CV Sample and run deploy-cv-model-training-pipeline.yml

### Expected Output

Expecting sample to run succesfully and train the model

### Versions

as per MLOps-V2 accelerator and project templates

### Which platform are you using for deploying your infrastrucutre?

GitHub Actions (GitHub)

### What are you using for deploying your infrastrucutre?

Terraform

### Are you using Azure ML CLI v2 or Azure ML Python SDK v2

Azure ML CLI v2

### Describe the example that you are trying to run?

prebuilt CV Example
[Job_train_OutputsAndLogs.zip](https://github.com/Azure/mlops-v2/files/10689554/Job_train_OutputsAndLogs.zip)

**Comment by sdonohoo** [comment]
This is due to a bug in mlflow integration with Azure. Currently, mlflow is automaticaly logging all parameters passed to the job by default. Any explicit mlflow.log_params() call that duplicates one of these parameters will cause this failure. Recommended workaround at this time is to remove explicit calls to mlflow.log_params() from the training code.

**Comment by setuc** [comment]
I am assuming this is resolved for you @jplummer01
