### ISSUE TITLE
Jenkins Pipeline 

### ISSUE THREAD

**Issue by MuMu2807** [Azure/mlops-v2#94]
Hi Team,

We were requested to use Jenkins pipeline instead of Azure devops pipeline for configuring Infra, Model training and Deployment. Here in Azure devops pipeline Yaml script, we are calling templates to execute a particular task. Whether this mlops v2 template based approach would be applicable via Jenkins pipelines also

**Comment by setuc** [comment]
Yes, they are certainlyy doable. You can make use of the CLI v2 / SDK to run through these pipelines. The key requirement of this is going to be working with Azure Service Principal. If you look at either of the getting started documentation with Azure DevOps (ADO) or GitHub Actions (GHA), you will notice that we use service principal to authenticate [Link](https://github.com/Azure/mlops-v2/blob/main/documentation/deployguides/README.md)

Once you have authenticated, you can run any azure CLI command. We store the secret appropriately. [Here ](https://learn.microsoft.com/en-us/azure/developer/jenkins/deploy-to-azure-app-service-using-azure-cli) is one example to deploy WebApp with Jenkins on Azure. so Instead of WebApp, you can deploy the training/deployment configurations on AzureML. 

You can alternatively use Managed Identity for authentication while working with Python Code. You can follow numerous examples of authenticating with Azure Identity package. One such reference would cann be found [here ](https://learn.microsoft.com/en-us/azure/machine-learning/how-to-setup-authentication?tabs=sdk). Don't use InteractiveAuthentication in the MLOPs pipeline.
